name: "default-svc-cluster-local-network"

version: 2.2.1

client:

  organization: org1

  logging:
    level: debug
  
  cryptoconfig:
    path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
    # and enrollments are performed elsewhere.
    path: "/tmp/state-store"

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/peerOrganizations/org1/peers/peer0-org1/msp
    
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  
  tlsCerts:
    systemCertPool: true

channels:

  mainchannel:

    peers:
      peer0-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
  
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 1000ms
          maxBackoff: 10s
          backoffFactor: 2.0

organizations:
  org1:
    mspid: org1
    cryptopath: peerOrganizations/org1/users/Admin@org1/msp
    peers:
      - peer0-org1
      - peer1-org1
  org2:
    mspid: org2
    cryptopath: peerOrganizations/org2/users/Admin@org2/msp
    peers:
      - peer0-org2
      - peer1-org2

orderers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
  
  orderer0:
    grpcOptions:
      ssl-target-name-override: orderer0
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

  
  orderer1:
    grpcOptions:
      ssl-target-name-override: orderer1
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

  
  orderer2:
    grpcOptions:
      ssl-target-name-override: orderer2
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

peers:

  _default:
    grpcOptions:
      keep-alive-time: 1s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    
  peer0-org1:
    url: https://peer0-org1:7051
    grpcOptions:
      ssl-target-name-override: peer0-org1
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/peerOrganizations/org1/msp/tlscacerts/org1-ca-7054.pem

  peer1-org1:
    url: https://peer0-org1:8051
    grpcOptions:
      ssl-target-name-override: peer1-org1
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/peerOrganizations/org1/msp/tlscacerts/org1-ca-7054.pem

    
  peer0-org2:
    url: https://peer0-org2:9051
    grpcOptions:
      ssl-target-name-override: peer0-org2
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/peerOrganizations/org2/msp/tlscacerts/org2-ca-7054.pem

  peer1-org2:
    url: https://peer1-org2:10051
    grpcOptions:
      ssl-target-name-override: peer1-org2
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/nick/Projects/k8s-hyperledger-fabric-2.2/crypto-config/peerOrganizations/org2/msp/tlscacerts/org2-ca-7054.pem

# entityMatchers:

#   peer:
#     - pattern: (\w*)peer0-org1-service(\w*)
#       urlSubstitutionExp: localhost:7051
#       sslTargetOverrideUrlSubstitutionExp: peer0-org1-service
#       mappedHost: peer0-org1-service

#     - pattern: (\w*)peer1-org1-service(\w*)
#       urlSubstitutionExp: localhost:8051
#       sslTargetOverrideUrlSubstitutionExp: peer1-org1-service
#       mappedHost: peer1-org1-service

#     - pattern: (\w*)peer0-org2-service(\w*)
#       urlSubstitutionExp: localhost:9051
#       sslTargetOverrideUrlSubstitutionExp: peer0-org2-service
#       mappedHost: peer0-org2-service

#     - pattern: (\w*)peer1-org2-service(\w*)
#       urlSubstitutionExp: localhost:10051
#       sslTargetOverrideUrlSubstitutionExp: peer1-org2-service
#       mappedHost: peer1-org2-service

#   orderer:
#     - pattern: (\w*)orderer0-service(\w*)
#       urlSubstitutionExp: localhost:7050
#       sslTargetOverrideUrlSubstitutionExp: orderer0-service
#       mappedHost: orderer0-service

#     - pattern: (\w*)orderer1-service(\w*)
#       urlSubstitutionExp: localhost:8050
#       sslTargetOverrideUrlSubstitutionExp: orderer1-service
#       mappedHost: orderer1-service
      
#     - pattern: (\w*)orderer2-service(\w*)
#       urlSubstitutionExp: localhost:9050
#       sslTargetOverrideUrlSubstitutionExp: orderer2-service
#       mappedHost: orderer2-service

