apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels: {
    component: api
  }
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      volumes:
        - name: host-mount
          persistentVolumeClaim:
            claimName: efs-burst-persistent-volume-claim
      containers:
        - name: api
          image: happilymarrieddadudemy/udemy-node-api:8e71de08c3e12143db009dd22bb2feb463099ec5
          env:
              - name: ENV
                value: prod
          #   - name: HYPERLEDGER_CONFIG_PATH
          #     value: /files/config.yaml
          volumeMounts:
            - mountPath: /files
              name: host-mount
              subPath: files
            - mountPath: /tmp/crypto
              name: host-mount
              subPath: files/scripts/crypto-config
