apiVersion: v1
kind: Service
metadata:
  name: org2-ca-service
  labels: {
    component: org2,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: org2
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
