version: '2'

networks:
  fabric-ca:

services:
  hp-ca:
    image: hyperledger/fabric-ca:1.4.7
    container_name: hp-ca
    ports:
      - 7057:7054
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - USERNAME=admin
      - PASSWORD=adminpw
      - CSR_HOSTS=hp-ca
    volumes:
      - ../../state/ca/hp/server:/etc/hyperledger/fabric-ca-server
      - ../../scripts:/scripts
    command: sh -c '/scripts/start-root-ca.sh'
    networks:
      - fabric-ca
  # Clients
  hp-client:
    tty: true
    image: hyperledger/fabric-ca:1.4.7
    container_name: hp-client
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - ORG_NAME=hp
      - CA_SCHEME=https
      - CA_URL=hp-ca:7054
      - CA_USERNAME=admin
      - CA_PASSWORD=adminpw
      - CA_CERT_PATH=/etc/hyperledger/fabric-ca-server/tls-cert.pem
    volumes:
      - ../../state/ca/hp/client:/etc/hyperledger/fabric-ca-client
      - ../../scripts:/scripts
      - ../../state/ca/hp/server:/etc/hyperledger/fabric-ca-server
      - ../../crypto-config:/etc/hyperledger/fabric-ca/crypto-config
    command: sh -c '/scripts/start-org-client.sh'
    networks:
      - fabric-ca
    depends_on:
      - hp-ca

