Organizations:
    - &orderer
        Name: orderer
        ID: orderer
        MSPDir: /host/files/crypto-config/ordererOrganizations/orderer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('orderer.member')"
            Writers:
                Type: Signature
                Rule: "OR('orderer.member')"
            Admins:
                Type: Signature
                Rule: "OR('orderer.admin')"
    - &ibm
        Name: ibm
        ID: ibm
        MSPDir: /host/files/crypto-config/peerOrganizations/ibm/msp
        AnchorPeers:
            - Host: peer0-ibm-service
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ibm.member')"
            Writers:
                Type: Signature
                Rule: "OR('ibm.member')"
            Admins:
                Type: Signature
                Rule: "OR('ibm.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ibm.member')"
    - &oracle
        Name: oracle
        ID: oracle
        MSPDir: /host/files/crypto-config/peerOrganizations/oracle/msp
        AnchorPeers:
            - Host: peer0-oracle-service
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('oracle.member')"
            Writers:
                Type: Signature
                Rule: "OR('oracle.member')"
            Admins:
                Type: Signature
                Rule: "OR('oracle.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('oracle.member')"
    - &hp
        Name: hp
        ID: hp
        MSPDir: /host/files/crypto-config/peerOrganizations/hp/msp
        AnchorPeers:
            - Host: peer0-hp-service
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('hp.member')"
            Writers:
                Type: Signature
                Rule: "OR('hp.member')"
            Admins:
                Type: Signature
                Rule: "OR('hp.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('hp.member')"

Capabilities:
    Global: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer0-service
              Port: 7050
              ClientTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/tls/server.crt
              ServerTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/tls/server.crt
            - Host: orderer1-service
              Port: 7050
              ClientTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer1/tls/server.crt
              ServerTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer1/tls/server.crt
            - Host: orderer2-service
              Port: 7050
              ClientTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer2/tls/server.crt
              ServerTLSCert: /host/files/crypto-config/ordererOrganizations/orderer/orderers/orderer2/tls/server.crt
    Addresses:
        - orderer0:7050-service
        - orderer1:7050-service
        - orderer2:7050-service
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
        - *orderer
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    MainChannel:
        Consortium: MAIN
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ibm
                - *oracle
                - *hp
            Capabilities:
                <<: *ApplicationCapabilities

