apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels: {
    component: web
  }
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: happilymarrieddadudemy/udemy-web-app:2cf03a7362c76a72b630b8ae1b06545f49a368db